name: "Build and publish Dotnet 6"
description: "Build and publish Dotnet 6 web apps"

inputs:
  sitename:
    description: "sitename bijv. help.bookingmonser.nl"
    required: true
runs:
  using: "composite"
  steps:
  runs-on: bookingmonster
  - uses: actions/checkout@v3
  - name: Setup .NET
    uses: actions/setup-dotnet@v2
    with:
      dotnet-version: 6.0.x
  - name: Restore dependencies
    run: dotnet restore 
  - name: Build
    run: dotnet build --no-restore
  - name: dotnet publish
    run: dotnet publish -c Release -o c:/drop/${{inputs.sitename}}
