name: "Build and publish Dotnet 6"
description: "Build and publish Dotnet 6 web apps"

inputs:
  sitename:
    description: "sitename bijv. help.bookingmonser.nl"
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Setup .NET
    uses: actions/setup-dotnet@v2
    with:
      dotnet-version: 6.0.x
      
  - name: Restore dependencies
    shell: pwsh
    run: dotnet restore 
    
  - name: Build
    shell: pwsh
    run: dotnet build --no-restore
    
  - name: dotnet publish
    shell: pwsh
    run: dotnet publish -c Release -o c:/drop/${{inputs.sitename}}
